apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gv6d
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-gv6d@sha256:eb5dd055273a8accd17147aea5b8cd310bd6843a68b0cbb6531235a0b47e7df2
        name: my-nodejs
        resources: {}
status: {}
